name: flutter_async_storage
version: 1.0.0
description: >
  Access data stored in React Native AsyncStorage from Flutter.
repository: https://github.com/google/flutter_async_storage

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
      sdk: flutter
  crypto: ^3.0.0
  disposables: ^1.0.0
  meta: ^1.3.0
  path_provider: ^2.0.0
  platform: ^3.0.0
  sqflite: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter